# 9. NumPy 高级索引

In [1]:
#整数数组索引 
import numpy as np
 
x = np.array([[1,2],[3,4],[5,6]])
print(x)
y = x[[0,1,2],[0,1,0]]
print(y)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [10]:
x = np.arange(12)
x = x.reshape(4,3)
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]
print(y)

[[ 0  2]
 [ 9 11]]


In [12]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a[1:3,1:3]
c = a[1:3,[1,2]]
d = a[...,1:]
print(b)
print(c)
print(d)

[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [13]:
#布尔索引

x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print("我们的数组是：")
print(x)
print("\n")
#现在我们会打印大于5的元素
print("大于5的元素")
print(x[x>5])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于5的元素
[ 6  7  8  9 10 11]


In [14]:
a = np.array([np.nan,1,2,np.nan,3,4,5])
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [15]:
a = np.array([1,2+6j,5,3.5+5j])
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


花式索引

In [22]:
#1.传入顺序索引数组

x = np.arange(32).reshape((8,4))
print(x[[4,2,1,7,3,0]])

[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]
 [12 13 14 15]
 [ 0  1  2  3]]


In [24]:
#2.传入倒序索引数组

print(x[[-4,-2,-1,-7]])

[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]


In [25]:
#3.传入多个索引数组（要使用np.ix_)
print(x[np.ix_([1,5,7,2],[0,3,1,2])])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
