# 菜鸟教程 Numpy教程

# #1. NumPy Ndarry对象

In [1]:
import numpy as np

In [10]:
a = np.array([1,2,3])
b = np.array([[1],[2],[3]],order = 'F')
print(a)
print(b)

[1 2 3]
[[1]
 [2]
 [3]]


In [9]:
#多于一个维度
c = np.array([[1,2],[3,4]])
print(c)

[[1 2]
 [3 4]]


In [11]:
#最小维度
d = np.array([1,2,3,4,5],ndmin = 2)
print(d)

[[1 2 3 4 5]]


In [12]:
#dtype参数
e = np.array([1,2,3],dtype = complex)
print(e)

[1.+0.j 2.+0.j 3.+0.j]
