# 20. NumPy 副本和视图

副本是一个数据的完整的拷贝，如果我们对副本进行修改，它不会影响到原始数据，物理内存不在同一位置。
视图是数据的一个别称或引用，通过该别称或引用亦便可访问、操作原有数据，但原有数据不会产生拷贝。如果我们对视图进行修改，它会影响到原始数据，物理内存在同一位置。

视图一般发生在：
1.numpy 的切片操作返回原数据的视图。
2.调用 ndarray 的 view() 函数产生一个视图。 

副本一般发生在：
1.Python 序列的切片操作，调用deepCopy()函数。
2.调用 ndarray 的 copy() 函数产生一个副本。 

无复制
简单的赋值不会创建数组对象的副本。 相反，它使用原始数组的相同id()来访问它。 id()返回 Python 对象的通用标识符，类似于 C 中的指针。
此外，一个数组的任何变化都反映在另一个数组上。 例如，一个数组的形状改变也会改变另一个数组的形状。

In [2]:
import numpy as np

a = np.arange(6)
print("我们的数组是：")
print(a)
print("调用id()函数：")
print(id(a))
print("a赋值给b")
b = a
print(b)
print("b拥有相同id():")
print(id(b))
print("修改b的形状：")
b.shape = 3,2
print(b)
print("a的形状也修改了：")
print(a)

我们的数组是：
[0 1 2 3 4 5]
调用id()函数：
2354553304448
a赋值给b
[0 1 2 3 4 5]
b拥有相同id():
2354553304448
修改b的形状：
[[0 1]
 [2 3]
 [4 5]]
a的形状也修改了：
[[0 1]
 [2 3]
 [4 5]]


视图或浅拷贝
ndarray.view() 方会创建一个新的数组对象，该方法创建的新数组的维数更改不会更改原始数据的维数。

In [3]:
#最开始a是个3x2的数组
a = np.arange(6).reshape(3,2)
print("数组a:")
print(a)
print("创建a的视图：")
b = a.view()
print(b)
print("两个数组的id()不同：")
print("a的id():")
print(id(a))
print("b的id():")
print(id(b))
#修改b的形状，并不会修改a
b.shape = 2,3
print("b的形状：")
print(b)
print("a的形状：")
print(a)

数组a:
[[0 1]
 [2 3]
 [4 5]]
创建a的视图：
[[0 1]
 [2 3]
 [4 5]]
两个数组的id()不同：
a的id():
2354553305168
b的id():
2354553305088
b的形状：
[[0 1 2]
 [3 4 5]]
a的形状：
[[0 1]
 [2 3]
 [4 5]]


使用切片创建视图修改数据会影响到原始数组：

In [5]:
arr = np.arange(12)
print("我们的数组：")
print(arr)
print("创建切片：")
a = arr[3:]
b = arr[3:]
a[1]=123
b[2]=231
print(arr)
print(id(a),id(b),id(arr[3:]))

我们的数组：
[ 0  1  2  3  4  5  6  7  8  9 10 11]
创建切片：
[  0   1   2   3 123 231   6   7   8   9  10  11]
2354553306368 2354553305168 2354553305248


副本或深拷贝
ndarray.copy() 函数创建一个副本。 对副本数据进行修改，不会影响到原始数据，它们物理内存不在同一位置。

In [6]:
a = np.array([[10,10],[2,3],[4,5]])
print("数组a:")
print(a)
print("创建a的深度副本：")
b = a.copy()
print("数组b:")
print(b)
#b与a不共享内容
print("我们能够写入b来写入a吗？")
print(b is a)
print("修改b的内容：")
b[0,0]=100
print("修改后的b数组：")
print(b)
print("a保持不变：")
print(a)

数组a:
[[10 10]
 [ 2  3]
 [ 4  5]]
创建a的深度副本：
数组b:
[[10 10]
 [ 2  3]
 [ 4  5]]
我们能够写入b来写入a吗？
False
修改b的内容：
修改后的b数组：
[[100  10]
 [  2   3]
 [  4   5]]
a保持不变：
[[10 10]
 [ 2  3]
 [ 4  5]]
