# 22. NumPy 线性代数

NumPy 提供了线性代数函数库 linalg，该库包含了线性代数所需的所有功能，可以看看下面的说明：
函数 	         描述
dot 	       两个数组的点积，即元素对应相乘。
vdot 	       两个向量的点积
inner 	       两个数组的内积
matmul 	       两个数组的矩阵积
determinant 	  数组的行列式
solve 	       求解线性矩阵方程
inv 	       计算矩阵的乘法逆矩阵

In [2]:
import numpy.matlib
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(np.dot(a,b))
#等价于[[1*11+2*13,1*12+2*14],[3*11+4*13,3*12+4*14]]

[[37 40]
 [85 92]]


numpy.vdot()
numpy.vdot() 函数是两个向量的点积。 如果第一个参数是复数，那么它的共轭复数会用于计算。 如果参数是多维数组，它会被展开。

In [3]:
#vdot将数组展开计算内积
print(np.vdot(a,b))
#等价于1*11+2*12+3*13+4*14=130

130


numpy.inner()
numpy.inner() 函数返回一维数组的向量内积。对于更高的维度，它返回最后一个轴上的和的乘积。

In [ ]:
print(np.inner(np.array([1,2,3]),np.array([0,1,0])))
#等价于1*0+2*1+3*0

In [6]:
#多维数组实例
a = np.array([[1,2],[3,4]])
print("数组a：")
print(a)
b = np.array([[11,12],[13,14]])
print("数组b：")
print(b)
print("内积：")
print(np.inner(a,b))

#内积计算公式
# 1*11+2*12，1*13+2*14
# 3*11+4*12，3*13+4*14

数组a：
[[1 2]
 [3 4]]
数组b：
[[11 12]
 [13 14]]
内积：
[[35 41]
 [81 95]]


numpy.matmul
numpy.matmul 函数返回两个数组的矩阵乘积。 虽然它返回二维数组的正常乘积，但如果任一参数的维数大于2，则将其视为存在于最后两个索引的矩阵的栈，并进行相应广播。
另一方面，如果任一参数是一维数组，则通过在其维度上附加 1 来将其提升为矩阵，并在乘法之后被去除。
对于二维数组，它就是矩阵乘法。

In [7]:
a = [[1,0],[0,1]]
b = [[4,1],[2,2]]
print(np.matmul(a,b))

[[4 1]
 [2 2]]


In [8]:
#二维和一维运算
a = [[1,0],[0,1]]
b = [1,2]
print(np.matmul(a,b))
print(np.matmul(b,a))

[1 2]
[1 2]


In [9]:
#维度大于2的数组
a = np.arange(8).reshape(2,2,2)
b = np.arange(4).reshape(2,2)
print(np.matmul(a,b))

[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]


In [10]:
a = np.array([[1,2],[3,4]])
print(np.linalg.det(a))

-2.0000000000000004


In [12]:
b = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(b)
print(np.linalg.det(b))
print(6*(-2*7 - 5*8)-1*(4*7 - 5*2)+1*(4*8 - -2*2))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0
-306


numpy.linalg.solve()
numpy.linalg.solve() 函数给出了矩阵形式的线性方程的解

numpy.linalg.inv()
numpy.linalg.inv() 函数计算矩阵的乘法逆矩阵。
逆矩阵（inverse matrix）：设A是数域上的一个n阶矩阵，若在相同数域上存在另一个n阶矩阵B，使得： AB=BA=E ，则我们称B是A的逆矩阵，而A则被称为可逆矩阵。注：E为单位矩阵。

In [13]:
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)
print(x)
print(y)
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [15]:
a = np.array([[1,1,1],[0,2,5],[2,5,-1]])
print("数组a：")
print(a)
ainv = np.linalg.inv(a)

print("a的逆：")
print(ainv)

print("矩阵b：")
b = np.array([[6],[-4],[27]])
print(b)

print("计算：A^(-1)B：")
x = np.linalg.solve(a,b)
print(x)
#这就是线性方程x=5,y=3,z=-2的解
y=np.dot(ainv,b)
print(y)

数组a：
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
a的逆：
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
矩阵b：
[[ 6]
 [-4]
 [27]]
计算：A^(-1)B：
[[ 5.]
 [ 3.]
 [-2.]]
[[ 5.]
 [ 3.]
 [-2.]]
