# 3. NumPy 数组属性

NumPy 数组的维数称为秩（rank），一维数组的秩为 1，二维数组的秩为 2，以此类推。
在 NumPy中，每一个线性的数组称为是一个轴（axis），也就是维度（dimensions）。

In [2]:
#ndarry.ndim
#ndarry.ndim用于返回数组的维数，等于秩

In [23]:
import numpy as np
a = np.arange(24) #生成0-23的数
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [24]:
print(a.ndim) #a 现在只有一个维度
#现在调整其大小
b = a.reshape(2,4,3) #b 现在有三个维度
print(b)
print(b.ndim)

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3


In [25]:
print(b[1])

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [26]:
#ndarray.shape 表示数组的维度
print(b.shape)

(2, 4, 3)


In [27]:
#调整数组大小
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [31]:
c = b.reshape(4,3,2)
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [32]:
#ndarray.itemsize
#ndarray.itemsize 以字节的形式返回数组中每一个元素的大小

In [33]:
#数组的dtype为int8（一个字节）
x = np.array([1,2,3,4,5],dtype = np.int8)
print(x.itemsize)

y = np.array([1,2,3,4,5],dtype = np.float64)
print(y.itemsize)

1
8


In [34]:
#ndarray.flags
#ndarray.flags 返回 ndarray 对象的内存信息，包含以下属性：

In [35]:
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
