# 4. NumPy 创建数组

In [1]:
import numpy as np
x = np.empty([3,2],dtype = int)
print(x)

[[-1142518560         319]
 [-1111177232         319]
 [-1138978656         319]]


numpy.zeros
创建指定大小的数组，数组元素以 0 来填充：
numpy.zeros(shape, dtype = float, order = 'C')

In [5]:
#默认浮点数
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [6]:
#设置类型为整数
y = np.zeros((5,),dtype = np.int)
print(y)

[0 0 0 0 0]


In [7]:
#自定义数据类型
z = np.zeros((2,2),dtype = [('x','i4'),('y','i4')])
print(z)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


numpy.ones
创建指定形状的数组，数组元素以 1 来填充：
numpy.ones(shape, dtype = None, order = 'C')

In [8]:
#默认为浮点数
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [11]:
#自定义类型
y = np.ones([2,2],dtype = int)
print(y)

[[1 1]
 [1 1]]


In [13]:
#自定义数据类型
z = np.ones((2,2),dtype = [('x','i4')])
print(z)

[[(1,) (1,)]
 [(1,) (1,)]]


In [17]:
print(z[1,1])

(1,)
