# 5.NumPy 从已有的数组创建数组

numpy.asarray
numpy.asarray 类似 numpy.array，但 numpy.asarray 参数只有三个，比 numpy.array 少两个。
numpy.asarray(a, dtype = None, order = None)

In [2]:
#将列表转换为ndarray
import numpy as np

x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


In [3]:
#将元组转换为ndarray

x = (1,2,3)
a = np.asarray(x)
print(a)

[1 2 3]


In [4]:
#将元组列表转换为ndarray

x = [(1,2,3),(4,5)]
a = np.asarray(x)
print(a)

[(1, 2, 3) (4, 5)]


In [7]:
#设置了dtype

x = [1,2,3]
a = np.asarray(x,dtype = float)
print(a)

[1. 2. 3.]


numpy.frombuffer
numpy.frombuffer 用于实现动态数组。
numpy.frombuffer 接受 buffer 输入参数，以流的形式读入转化成 ndarray 对象。
numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)
注意：buffer 是字符串的时候，Python3 默认 str 是 Unicode 类型，所以要转成 bytestring 在原 str 前加上 b。

In [11]:
s = b"Hello World"
a = np.frombuffer(s,dtype = 'S1')
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [13]:
b = np.frombuffer(s,dtype = 'S2',count = 4,offset = 1)
print(b)

[b'el' b'lo' b' W' b'or']


numpy.fromiter
numpy.fromiter 方法从可迭代对象中建立 ndarray 对象，返回一维数组。
numpy.fromiter(iterable, dtype, count=-1)

In [15]:
#使用range函数创建列表对象
list = range(5)
it = iter(list)
print(it)

#使用迭代器创建ndarray
x = np.fromiter(it,dtype = float)
print(x)

[0. 1. 2. 3. 4.]
