# 6.NumPy 从数值范围创建数组

numpy.arange
numpy 包中的使用 arange 函数创建数值范围并返回 ndarray 对象，函数格式如下：
numpy.arange(start, stop, step, dtype)

In [3]:
#生成0到5的数组
import numpy as np

x = np.arange(5)
print(x)

[0 1 2 3 4]


In [4]:
#设置了起始值、终止值及步长

x = np.arange(10,20,2)
print(x)

[10 12 14 16 18]


numpy.linspace
numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的，格式如下：
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [7]:
a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [8]:
a = np.linspace(1,1,10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
a = np.linspace(10,20,5,endpoint = False)
print(a)

[10. 12. 14. 16. 18.]


In [10]:
a = np.linspace(10,20,5,endpoint = True)
print(a)

[10.  12.5 15.  17.5 20. ]


In [11]:
a = np.linspace(1,10,10,retstep = True)
print(a)

#拓展例子

b = np.linspace(1,10,10).reshape([10,1])
print(b)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


numpy.logspace
numpy.logspace 函数用于创建一个于等比数列。格式如下：
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)

In [17]:
#默认底数是10
a = np.logspace(1.0,2.0,num = 10)
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [15]:
a = np.logspace(0,9,10,base = 2)
print(a)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


ValueError: could not convert string to float: '6.1101,17.592'