# 8. NumPy 切片和索引

ndarray对象的内容可以通过索引或切片来访问和修改，与 Python 中 list 的切片操作一样。

In [1]:
import numpy as np

In [3]:
a = np.arange(10)
s = slice(2,7,2) #从索引2开始到索引7停止，间隔为2
print(a[s])

[2 4 6]


In [4]:
b = a[2:7:2]
print(b)

[2 4 6]


In [5]:
print(a[2:])

[2 3 4 5 6 7 8 9]


In [6]:
print(a[2:5])

[2 3 4]


In [8]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
#从某个索引处开始切割
print('从数组索引a[1:]处开始切割')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
从数组索引a[1:]处开始切割
[[3 4 5]
 [4 5 6]]


In [9]:
print(a[...,1])#第2列元素

[2 4 5]


In [10]:
print(a[:,1])#第2列元素

[2 4 5]


In [11]:
print(a[1,...])#第2行元素

[3 4 5]


In [12]:
print(a[1,:])#第2行元素

[3 4 5]


In [13]:
print(a[...,1:])#第2列及剩下的所有元素

[[2 3]
 [4 5]
 [5 6]]


In [15]:
#在多维数组的切片中，使用 , 区分维数。
a = np.arange(0,12)
a.shape=(3,4)
print(a)
print(a[0:2,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [5 6]]
