In [3]:
#numpy 属性
import numpy as np
array = np.array([[1,2,3],
                  [2,3,4]])
print(array)
print('number of dim:',array.ndim)#纬度
print('shape',array.shape)
print('size',array.size)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape (2, 3)
size 6


In [29]:
#numpy的创建array
import numpy as np

a = np.array([[2,3,4],
              [4,5,6]],
              dtype=np.int)
print(a)
b = np.zeros((3,3),dtype=np.int)
print(b)
c = np.ones((3,3),dtype=np.int)
print(c)
d = np.eye(3)
print(d)
e = np.arange(10,22,2).reshape(2,3)
print(e)
f = np.linspace(1,10,12).reshape((3,4))
print(f)

[[2 3 4]
 [4 5 6]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[10 12 14]
 [16 18 20]]
[[ 1.          1.81818182  2.63636364  3.45454545]
 [ 4.27272727  5.09090909  5.90909091  6.72727273]
 [ 7.54545455  8.36363636  9.18181818 10.        ]]


In [41]:
#numpy 基本运算
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)
c = a+b
print(c)
d = b**2
print(d)
e = np.sin(a)
print(e)
print(b<3)
f = np.array([[1,1],[0,1]])
g = np.arange(4).reshape(2,2)

h = f*g
i = np.dot(f,g)
print(h)
print(i)

j = np.random.random((2,4))
print(j)
print(np.sum(j))
print(np.sum(j,axis=0))
print(np.sum(j,axis=1))

[10 20 30 40] [0 1 2 3]
[10 21 32 43]
[0 1 4 9]
[-0.54402111  0.91294525 -0.98803162  0.74511316]
[ True  True  True False]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[0.66067431 0.9004411  0.15867928 0.14265259]
 [0.82809341 0.3399452  0.8934748  0.12295546]]
4.046916156013488
[1.48876772 1.24038631 1.05215408 0.26560805]
[1.86244728 2.18446887]


In [13]:
#numpy的基本运算2
import numpy as np
A = np.arange(14,2,-1).reshape(3,4)
print(A)
print(np.argmin(A))#最小值索引
print(np.argmax(A))#最大值索引
print(np.mean(A))#求平均值
print(np.mean(A,axis=0))#对列进行计算
print(np.mean(A,axis=1))#对行进行计算
print(np.median(A))#中位数
print(np.cumsum(A))#逐项累加
print(np.diff(A))#累差
print(np.nonzero(A))#非零数的位置
print(np.sort(A))#逐行排序
print(np.transpose(A))#求A的转置
print(A.T)#求A的转置
print(np.clip(A,5,9))#小于5等于5，大于9等于9，中间不变

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
11
0
8.5
[10.  9.  8.  7.]
[12.5  8.5  4.5]
8.5
[ 14  27  39  50  60  69  77  84  90  95  99 102]
[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [ ]:
#numpy的索引
